<a href="https://colab.research.google.com/github/Cesar17188/EDA/blob/master/Regresion_y_evaluacion_de_hipotesis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regresión y evaluación de hipótesis

* Neural Network Regressior
* Decision Tree Regression
* LASSO Regression
* Ridge Regression
* ElasticNet Regression


In [1]:
import pandas as pd
from sklearn import datasets
import numpy as np

In [2]:
iris=datasets.load_iris()

In [5]:
data=pd.DataFrame(iris.data)
data.columns=iris.feature_names
data['target']=iris.target

In [8]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
data['name_t']=data['target'].map({0:'setosa',1:'versicolor',2:'virginica'})

In [11]:
data.head()

sepal length (cm)  sepal width (cm)  ...  target  name_t
0                5.1               3.5  ...       0  setosa
1                4.9               3.0  ...       0  setosa
2                4.7               3.2  ...       0  setosa
3                4.6               3.1  ...       0  setosa
4                5.0               3.6  ...       0  setosa

[5 rows x 6 columns]

In [12]:
from sklearn.model_selection import train_test_split

In [14]:
target=['target','name_t']
desc=list(set(list(data.columns))-set(target))

In [15]:
desc

['sepal width (cm)',
 'sepal length (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [16]:
x=data[desc].values
y=data['target'].values

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=40)

In [18]:
from sklearn.tree import DecisionTreeRegressor

In [19]:
reg_1=DecisionTreeRegressor(max_depth=4)
reg_1.fit(x_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=4,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [20]:
predict_train=reg_1.predict(x_train)
predict_test=reg_1.predict(x_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix

In [23]:
print(classification_report(y_test,predict_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        15

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [24]:
print(confusion_matrix(y_test,predict_test))

[[16  0  0]
 [ 0 14  0]
 [ 0  0 15]]
